# BeenThere API Configuration
server:
  port: 8080

spring:
  application:
    name: beenthere-api
  
  # R2DBC Configuration (reactive database)
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/beenthere}
    username: ${R2DBC_USERNAME:postgres}
    password: ${R2DBC_PASSWORD:postgres}
  
  # JDBC Configuration (for Flyway migrations only)
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/beenthere}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true


# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.beenthere: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# BeenThere Application Configuration
beenthere:
  # Google OAuth Configuration
  google:
    client-id: ${GOOGLE_CLIENT_ID:dummy-client-id}
    places:
      api-key: ${GOOGLE_PLACES_API_KEY:dummy-api-key}
  
  # Phone Hash Secret for HMAC-SHA256
  phone:
    hash-secret: ${PHONE_HASH_SECRET:dummy-secret-change-in-prod}
  
  # JWT Configuration  
  jwt:
    secret: ${JWT_SECRET:dummy-jwt-secret-change-in-prod}
    expiration-hours: ${JWT_EXPIRATION_HOURS:24}
  
  # AWS Configuration
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID:dummy-access-key}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:dummy-secret-key}
    region: ${AWS_REGION:us-east-1}
  
  # S3 Configuration
  s3:
    bucket: ${AWS_S3_BUCKET:dummy-bucket}

